// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwlarhwmxidpzibqtqzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3bGFyaHdteGlkcHppYnF0cXp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MDI2NDgsImV4cCI6MjA3MzA3ODY0OH0.tkVC9GxUtOVrzkhxA8_LmBbZ_EsLFqPM-88UnkK4-cY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});